# Generated by Django 4.2 on 2023-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadFileM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Перетащите сюда файл', upload_to='documents', verbose_name='Файл')),
            ],
        ),
        migrations.DeleteModel(
            name='ReadFile',
        ),
    ]
